---
- name: check if keys already exist
  shell: |
    set -o pipefail
    if [ -d /home/polkadex/.local/share/polkadex/chains/{{ polkadex_network_id }}/keystore ]; then
      ls /home/polkadex/.local/share/polkadex/chains/{{ polkadex_network_id }}/keystore -1U | wc -l
    else
      mkdir -p /home/polkadex/.local/share/polkadex/chains/{{ polkadex_network_id }}/
      chown -R polkadex:polkadex /home/polkadex/.local/share/polkadex
      echo 0
    fi
  args:
    executable: /bin/bash
  register: keystore_files
  changed_when: False

- name: initialize server keys
  import_role:
    name: polkadex-rotate-keys
  when: keystore_files.stdout == "0"
