- name: stop polkadex service
  systemd:
    name: polkadex.service
    state: stopped

- name: purge chain
  shell: |
    set -o pipefail
    /usr/local/bin/polkadex purge-chain -y
  become: yes
  become_user: polkadex
  args:
    executable: /bin/bash
  changed_when: False

- name: start polkadex service
  systemd:
    name: polkadex.service
    state: started
