---
- name: Wait for system ready
  hosts: all
  gather_facts: no
  tasks:
  - name: Wait for nodes to become reachable
    wait_for_connection:

- name: validator
  hosts: validator
  become: yes
  roles:
  - polkadex-validator

- name: nginx-auth
  hosts: validator
  become: yes
  strategy: free
  roles:
  - nginx-auth  

- name: node-exporter
  hosts: validator
  become: yes
  strategy: free
  roles:
  - { role: node-exporter, when: node_exporter_enabled|bool }
