- name: get command output
  shell: |
    set -o pipefail
    journalctl -u polkadex --no-pager > /root/polkadex.log
    tail -n 10000 /root/polkadex.log | grep "Waiting to import block"
  become: yes
  args:
    executable: /bin/bash
  changed_when: False
  register: command_output

- name: result
  debug:
    msg: "Command result: {{ command_output.stdout }}"

- name: remove log
  file:
    path: /root/polkadex.log
    state: absent
